Update Chart.js Version
superKalo/crypto-tab pull request #43
Opened 2024-07-08 13:35 UTC by ivelinmegdanov

**Updates Chart.js to the latest version. The changes include updating the Gulp tasks and modifying the code to accommodate any breaking changes introduced in the new version.**

- Updated: Chart.js to the latest version.
- Modified: Gulp tasks to copy the new version of Chart.js.
- Updated: Chart initialization code to use the new Chart.js API.

2024-07-24 19:57 UTC, superKalo commented
In the migrated (new) version, the tooltips that display min and max price per selected period are missing:
 
<img width="1117" alt="Screenshot 2024-07-24 at 22 54 23" src="https://github.com/user-attachments/assets/ba64b38f-5739-4475-8774-a741245c40bf">

2024-07-24 19:59 UTC, superKalo commented
In the migrated version, the tooltip styles look a bit messed up. How it looks now:

<img width="205" alt="Screenshot 2024-07-24 at 22 58 46" src="https://github.com/user-attachments/assets/4b33f78b-5213-4d67-b4c2-5a452d0291dc">

vs before:

<img width="243" alt="Screenshot 2024-07-24 at 22 58 53" src="https://github.com/user-attachments/assets/82496382-07b8-47eb-9f7e-aba99f33a231">

2024-07-24 20:01 UTC, superKalo commented on src/js/chart.js
> -                // we can't use the chart tooltip because there is only one tooltip per chart
Hm, why you deleted this comment?

2024-07-24 20:05 UTC, superKalo commented
There is an annoying hover effect when you hover over the data set:

https://github.com/user-attachments/assets/afa15650-e5bb-43a7-8168-f8d9c87e95a0

2024-07-24 20:09 UTC, superKalo commented on package.json
> +    "chart.js": "4.0.1",
Why this specific version? ChartJS v4.0.1 was released 2 years ago. The latest version is v4.4.3. Does migrating to the latest version give you any trouble?

2024-07-24 20:10 UTC, superKalo requested changes
So far so good! I added some feedback, please take a look when you have time :v:

2024-08-13 21:47 UTC, superKalo commented
Okay, it's a lot better now! I like the approach for displaying min and max price!

Can you please try to improve a bit the drawing of the permanent min and max tooltips?

They are just a tiny bit off in terms of 1) The triangle has a tiny space (probably less than 1px, but annoying) and 2) The text is not vertically centered (it feels just a bit more on the top).

Here's a permanent tooltip:

<img width="341" alt="Screenshot 2024-08-14 at 0 44 16" src="https://github.com/user-attachments/assets/1196ed15-408b-48a2-8f27-41068042bced">

vs a tooltip:

<img width="309" alt="Screenshot 2024-08-14 at 0 44 32" src="https://github.com/user-attachments/assets/d38b0cab-c657-442c-9a24-a8b7cd851de0">

2024-08-16 09:42 UTC, ivelinmegdanov commented
> Okay, it's a lot better now! I like the approach for displaying min and max price!
> 
> Can you please try to improve a bit the drawing of the permanent min and max tooltips?
> 
> They are just a tiny bit off in terms of 1) The triangle has a tiny space (probably less than 1px, but annoying) and 2) The text is not vertically centered (it feels just a bit more on the top).
> 
> Here's a permanent tooltip:
> <img alt="Screenshot 2024-08-14 at 0 44 16" width="341" src="https://private-user-images.githubusercontent.com/2548061/357582855-1196ed15-408b-48a2-8f27-41068042bced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTk3NjgsIm5iZiI6MTcyMzc5OTQ2OCwicGF0aCI6Ii8yNTQ4MDYxLzM1NzU4Mjg1NS0xMTk2ZWQxNS00MDhiLTQ4YTItOGYyNy00MTA2ODA0MmJjZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMDkxMTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGNhMmUwYmY3YWEyYjhiMjUyMDc4ZGI0MWZjODc4NTljMmU2YWQxMTQ1MjA3ZDM0YmZhZGMwNDc5Njg4YmUwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bJ9dX_TRPfmyb1nlJIWRvc_axuW_zZsgTOueMogStQs">
> 
> vs a tooltip from the lib (displays perfectly):
> <img alt="Screenshot 2024-08-14 at 0 44 32" width="309" src="https://private-user-images.githubusercontent.com/2548061/357582924-d38b0cab-c657-442c-9a24-a8b7cd851de0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTk3NjgsIm5iZiI6MTcyMzc5OTQ2OCwicGF0aCI6Ii8yNTQ4MDYxLzM1NzU4MjkyNC1kMzhiMGNhYi1jNjU3LTQ0MmMtOWEyNC1hOGI3Y2Q4NTFkZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMDkxMTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzljNjU4ZmNkODA3MTRjODk3ZTVjZGYwOTU1YzVhNTE3MzljN2U3MmU4ZmM0OTU2YTA5ZWJiZmNkNGI2YzhkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dfzi2xzWX10ILf8fIHpeYBA1CymlbtAsN_EqA4ZbkfQ">

Regarding the text, it appears to me that it’s consistent between both the permanent and hover tooltips,

Hover tooltip: 
![image](https://github.com/user-attachments/assets/ff8f3b90-6ded-40df-bb65-3a502c0de639)

Permanent tooltip:
![image](https://github.com/user-attachments/assets/6cf261dd-2cae-46b6-a1f3-f616719c51e2)

Overlap on both:
![image](https://github.com/user-attachments/assets/93fb40a1-af4e-4827-af31-7d8b72e13d64)
![image](https://github.com/user-attachments/assets/173f2f8c-7212-4fb0-8600-f615d0efcb46)

2024-08-16 12:02 UTC, bego1996 approved these changes

2024-08-19 20:14 UTC, superKalo approved these changes
All right, now it looks perfect 💎 Thank you!

2024-08-19 20:14 UTC, merged